# Generated by ariadne-codegen
# Source: queries.graphql

from pydantic import Field

from .base_model import BaseModel
from .fragments import ModelData


class UpdateModelComputeConfig(BaseModel):
    update_model_compute_config: "UpdateModelComputeConfigUpdateModelComputeConfig" = (
        Field(alias="updateModelComputeConfig")
    )


class UpdateModelComputeConfigUpdateModelComputeConfig(ModelData):
    pass


UpdateModelComputeConfig.model_rebuild()
